[package]
name = "kowalski-rs"
version = "0.1.0"
authors = ["Simon Pannek"]
edition = "2021"
description = ""
repository = "https://github.com/simonpannek/kowalski-rs"

[dependencies]
tracing = "0.1.30"
tracing-subscriber = "0.3.8"

[dependencies.serenity]
version = "0.10"
default-features = false
features = ["client", "gateway", "model", "rustls_backend", "unstable_discord_api"]

[dependencies.tokio]
version = "1.0"
features = ["macros", "rt-multi-thread"]
