[general]
# The owners of the bot
owners = [158280426551640064]

[commands]

# Global
# For the permissions field, use https://discordapi.com/permissions.html
[commands.ping]
description = "Ping the bot."
default_permission = true

[commands.about]
description = "Display information about the bot."
default_permission = true

[commands.module]
description = "Update the activated modules on this server."
default_permission = false
permission = "8"

# Bot management
[commands.sql]
description = "Execute a sql query."
module = "Owner"
default_permission = false
owner = true
